# Generated by Django 4.0.4 on 2022-06-15 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('associated_users', models.ManyToManyField(blank=True, related_name='students_in_a_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
