# Generated by Django 4.0.4 on 2022-06-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0008_alter_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='associated_users',
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
    ]
