# Generated by Django 4.0.4 on 2022-05-29 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2022, 5, 29, 14, 17, 52, 315212)),
        ),
    ]
