# Generated by Django 4.0.4 on 2022-05-29 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2022, 5, 29, 14, 19, 37, 395312)),
        ),
    ]
