# Generated by Django 4.0.4 on 2022-05-31 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime(2022, 5, 30, 20, 24, 9, 673281)),
        ),
    ]
